### ISSUE TITLE
Crossepg reverts to flash with BlackHole

### ISSUE THREAD

**Issue by wastez** [E2OpenPlugins/e2openplugin-CrossEPG#20]
After some time (could take 1-3 days) the setting reverts to flash.
I had this problem with all BlackHole Versions before. (1.6.6-1.7.4)

Maybe it would be possible to find a solution for this problem.

Currently i´m using the newest version of crossepg, but also used git272 and the problem was the same.

**Comment by amir931** [comment]
Hi thanks for your work
 Please add Chromiumos plugins and AnimationSetup to the beautiful openpli7 image for vuplus. In the image plugin panel 
vu+ ultimo4k 🙏🙏🙏👌
