### ISSUE TITLE
XEPGDB 

### ISSUE THREAD

**Issue by RobvanderDoes** [E2OpenPlugins/e2openplugin-CrossEPG#34]
As XEPGDB is no longer being maintained by the SIFteam it should be deleted from Cross.

**Comment by Schimmelreiter** [comment]
I totally agree.

**Comment by AbuBaniaz** [comment]
This has been done in OE-A version

https://github.com/oe-alliance/e2openplugin-CrossEPG/commit/c859da20b0cba390e9bfc7f609618ba52b7ead44
