### ISSUE TITLE
Open ATV 5.1 and Cross EPG 8.1.0 Compatabilty issue

### ISSUE THREAD

**Issue by p17blo** [E2OpenPlugins/e2openplugin-CrossEPG#39]
[crossepg.log.txt](https://github.com/E2OpenPlugins/e2openplugin-CrossEPG/files/128927/crossepg.log.txt)

When using Open ATV 5.1 and Cross EPG 8.1.0, during download the process stalls.  Firstly in the early stages (488kb) of 'Reading titles', but this appears to proceed past this point are an extended delay (around 3 minutes)

Then at 2.01mb of 'Reading summaries' and this stalls for maybe 10 minutes before apparently completing.

Having attempted this on a completely new build, I can report that the result is a partially completed EPG.

Log file attached

**Comment by andyblac** [comment]
wrong git, OpenATV do not use this version, OE-Alliane have there own version here.

https://github.com/oe-alliance/e2openplugin-CrossEPG

**Comment by p17blo** [comment]
Apoloigies, I didn't realise - Thank you for the steer.
